name: EmbodiedAI
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appdirs=1.4.4
  - bcrypt=3.2.0
  - blas=1.0
  - bokeh=2.4.2
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - cryptography=36.0.0
  - cytoolz=0.11.0
  - dask=2022.2.1
  - dask-core=2022.2.1
  - distributed=2022.2.1
  - entrypoints=0.3
  - fabric=2.5.0
  - freetype=2.11.0
  - fsspec=2022.2.0
  - giflib=5.2.1
  - heapdict=1.0.1
  - idna=3.3
  - intake=0.6.5
  - intel-openmp=2021.4.0
  - invoke=1.4.1
  - jinja2=3.0.3
  - jpeg=9d
  - jproperties=2.1.1
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - locket=0.2.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.2
  - ncurses=6.3
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.1
  - paramiko=2.7.2
  - partd=1.2.0
  - pillow=9.0.1
  - pip=21.2.4
  - psutil=5.8.0
  - pycparser=2.21
  - pynacl=1.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-snappy=0.6.0
  - python_abi=3.8
  - pytz=2021.3
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.27.1
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.8
  - sortedcontainers=2.4.0
  - sqlite=3.37.2
  - tblib=1.7.0
  - tk=8.6.11
  - toolz=0.11.2
  - tornado=6.1
  - typing_extensions=4.1.1
  - urllib3=1.26.8
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.9
