name: AI2Thor
channels:
  - conda-forge
  - defaults
dependencies:
  - ai2thor=4.2.0
  - aws-requests-auth=0.4.2
  - blas=2.113
  - blas-devel=3.9.0
  - botocore=1.24.32
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.1.2
  - cryptography=36.0.2
  - eigen=3.4.0
  - flask=2.1.1
  - fontconfig=2.13.96
  - freetype=2.10.4
  - gettext=0.21.0
  - glib=2.69.1
  - graphite2=1.3.14
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=2.8.1
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - itsdangerous=2.1.2
  - jinja2=3.1.1
  - jmespath=1.0.0
  - jpeg=9e
  - krb5=1.19.2
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libssh2=1.10.0
  - libtiff=4.2.0
  - libwebp-base=1.2.2
  - libxml2=2.9.12
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - msgpack-python=1.0.3
  - ncurses=6.3
  - numpy=1.16.6
  - olefile=0.46
  - openblas=0.3.18
  - opencv=4.5.4
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - pcre=8.45
  - pillow=7.2.0
  - pip=21.2.4
  - pixman=0.38.0
  - progressbar2=4.0.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-utils=3.1.0
  - python-xlib=0.28
  - python_abi=3.8
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.27.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - urllib3=1.26.9
  - werkzeug=2.1.1
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
